import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	const pluginId = "vaultrecall";
	console.log(`
Build complete. To install manually:

  1. Open your vault folder in Explorer / Finder.
  2. Navigate to  .obsidian/plugins/
  3. Create a folder named  ${pluginId}  (if it doesn't exist).
  4. Copy these three files into that folder:
       main.js
       manifest.json
       styles.css
  5. In Obsidian: Settings → Community plugins → reload, then enable
	   "StudyStream SR".
`);
	process.exit(0);
} else {
	await context.watch();
}
